### ISSUE TITLE
Spectrum plot

### ISSUE THREAD

**Issue by hb9dug** [Psynosaur/DATV-Red#14]
PlutoDVB2 firmware has an interesting hidden module: a spectrum plot display of the Pluto's RX input.

Maybe, this could be a option for making DATV-Red independent of the BATC server... but I'm not competent in this area of programming.

Attached is a flow to be added to DATV-Red V3 to control this option as well as the web spectrum plot keyboard commands.

The files of this module are under /www on the pluto.

73 qro de michel, hb9dug

[spectrum-plot-datv-red-v3.json](https://github.com/Psynosaur/DATV-Red/files/13499615/spectrum-plot-datv-red-v3.json)
[cmd-spectrum-plot.txt](https://github.com/Psynosaur/DATV-Red/files/13499616/cmd-spectrum-plot.txt)

**Comment by Psynosaur** [comment]
Hi

Thank you for pointing this out

I shall investigate

**Comment by Psynosaur** [comment]
![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/651cc096-e6bc-4efd-a572-baf4ed6e08ce)

Managed to include it into the project, as static html file.

This is a hack will, further play with it.

Changing TX SR changes RX symbol rates
