### ISSUE TITLE
Pilots and frame short in GSE mode

### ISSUE THREAD

**Issue by RookieMorph** [Psynosaur/DATV-Red#15]
Hi,
when in GSE mode, TS-Bitrate does not change when toggle pilots on/off or frame short/long.

73
Michael

**Comment by Psynosaur** [comment]
will look into this

**Comment by Psynosaur** [comment]
Hi

So finding are that TS expected rate topic no longer get messages sent to this topic once the radio entered GSE mode.

![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/f7574d6b-ca9c-4c72-971c-fdd75bea7793)

Switching back to dvbs2-ts restores normal behavior .

So it seem we should pick our settings in TS mode, then go to GSE.

Speaking of GSE, we need to only init it once per application / pluto reboot life cycle, I will try implement this

These are my observations, and I wouldn't want to go back to deriving the TS rate.

Regards
