### ISSUE TITLE
LNB polarisation

### ISSUE THREAD

**Issue by F5OEO** [Psynosaur/DATV-Red#19]
Please add polar control (https://github.com/F5OEO/pluto-ori-ps/wiki#minitiouner-control-with-longmynd-httpsgithubcomf5oeolongmynd) in order to switch to narrowband with LNB

**Comment by Psynosaur** [comment]
Hi

Added.

![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/230732da-cb22-44f7-93a7-48521d202229)
