### ISSUE TITLE
Signal treshold

### ISSUE THREAD

**Issue by F5OEO** [Psynosaur/DATV-Red#21]
For easy use, this threshold could use a percent , calculated thus between Min an Max.  An horizontal red line on spectrum could also help

**Comment by Psynosaur** [comment]
will add in next release.

did something similar with OT some time ago

![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/cb849263-1054-4161-97e3-9188da3557b7)

**Comment by Psynosaur** [comment]
Hi

Implemented.

Based on range from min and max of spectrum and divided into 100 steps, with a line to indicate the threshold
![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/6de356fa-6f11-4c9b-aafd-a492edbc12c7)

Will ship with 3.96
