### ISSUE TITLE
using the NVidia to encode using FFmpeg lib

### ISSUE THREAD

**Issue by OD5TB** [Psynosaur/DATV-Red#23]
the DATV-REd is not responding when selecting the libvvenc or hevc to use external hardware as Nvidia ....i tried to change the names as per ffmpeg -version in codec but did not work , using CPU to encode with lib265 is taking 90% of my intelcore i7 , it would be nice if ffmpeg h264 nvenc can let Nvidia can do this work ....
https://publit.io/community/blog/ffmpeg-with-cuda-and-gpu-accelerated-video-conversion
thanks 73
OD5TB

**Comment by Psynosaur** [comment]
update your NVidia driver.

Furthermore NVIDIA improvements have been done on v4.
