### ISSUE TITLE
Info bubble over profile buton

### ISSUE THREAD

**Issue by ranaud80** [Psynosaur/DATV-Red#24]
Hello,
Is it possible to make info bubble when mouse is over profil to make à larger descriptive of the profile ?

Thank's

**Comment by Psynosaur** [comment]
Hallo

Pre-sets can be named.

![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/4ed02bd4-f569-44aa-8562-5f6999a076ec)

Hope it helps
