### ISSUE TITLE
V4.8.5: Audio encoder

### ISSUE THREAD

**Issue by ON1AVO** [Psynosaur/DATV-Red#26]
Ohan,

Changing Audio channels to Mono / 5.1 / 7.1: ffmpeg fault, only Stereo no problem.

![image](https://github.com/Psynosaur/DATV-Red/assets/132191313/3a6e776b-f3af-4333-85fc-2c1e62d1a4cd)

**Comment by Psynosaur** [comment]
Hi

Oops, `-profile:a aac_he_v2` was erroneously applied to non stereo configs for `libfdk_aac`.

Will include fix next release.

Regards

**Comment by Psynosaur** [comment]
Hallo...

Fixed in latest commit

Will add back the `aac_he` and `aac_he_v2` profiles for `libfdk_aac` with greater constraints.
