### ISSUE TITLE
10 min nag and nodered Passwd,

### ISSUE THREAD

**Issue by plantjes1** [Psynosaur/DATV-Red#28]
I hope all is well and the baby gets bigger every day.

I have been very busy last months also but have played with your latest 4.86a

All is working fine like it used to.
I noticed you have put a passwd on the nodered.

I am using it mainly for local repeater work on 70cm or 23 cm and the time nag is quit irritating.
We are used to do overs for 2 or 3 hours on a evening.
A back talk channel taking care for the freq usage.

Please inform me how i can get around the nag...

**Comment by Psynosaur** [comment]
Hallo

Since you have the password now

![image](https://github.com/Psynosaur/DATV-Red/assets/26934113/62b65ca1-10b5-44ca-b253-21d01e28d5c8)

remove lines 6-11

cheers
