### ISSUE TITLE
Problem with DATV-Red

### ISSUE THREAD

**Issue by Jabieraru142** [Psynosaur/DATV-Red#30]
Hello: i am EA2ARU, Jabi and is impossible for me run the DATV-Red. The IP of my computer is: 192.168.1.90 and the IP of my Adalm-Pluto is: 192.168.1.220.
I send copies of my configs of device.json and setting.json.
Please send me instructions about how work with the last version of DATV-Red 4.9-1 ?

device.json:
{"tx":{"dvbs2 {"fec":"4/5","frame":"long","pilots":"0","sr":333000,"gainvariable":"0","fecmode":"fixed","fecrange":8,"tssourcemode":"0","tssourceaddress":"192.168.1.220:8282","digitalgain":0,"constel":"qpsk","ts":{"bitrate":528536},"firfilter":"1"},"stream":{"mode":"dvbs2-ts"},"frequency":2409250048,"gain":-9,"nco":-30,"offset":0},"rx":{"frequency":741926,"offset":-9749574000,"tsip":"230.0.0.2:1234","configIP":"230.0.0.2","ffplay_size":"426x240","ffplay_volume":8,"ffplay":false,"ffplay_ontop":true,"use_minitioune":true,"stream":{"mode":"webfft"},"sr":"10656000","tsip_host":"230.0.0.2"},"minitioune_path":"F:\\Radio\\QO-100\\minitiouner\\MiniTioune.exe","dvbs_gui_path":"F:\\Radio\\QO-100\\dvb-s_gui_amsat\\dvb-s_gui.exe","vlc_path":"C:\\Program Files\\VideoLAN\\VLC\\vlc.exe","ffmpeg_path":".\\ffmpeg\\ffmpeg.exe","ffplay_path":".\\ffmpeg\\ffplay.exe","ffprobe_path":".\\ffmpeg\\ffprobe.exe","sig_report_suffix":"1.4m offset","ffplay_path_linux":"./ffmpeg/ffplay","ffmpeg_path_linux":"./ffmpeg/ffmpeg","ffprobe_path_linux":"./ffmpeg/ffprobe","vlc_path_linux":"/usr/bin/vlc","fft_url":"wss://eshail.batc.org.uk/wb/fft","hosting_url":"","obs_path":"C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe"}

settings.json:
{"SR":333,"TSBITRATE":528.536,"VBITRATE":380.11,"IMAGESIZE":"960x540","ABITRATE":"48","CODEC":"hevc_nvenc","FPS":"25","AUDIO":"2","MODE":"qpsk","FEC":"4/5","audio_device":"CABLE Output (VB-Audio Virtual Cable)","video_device":"OBS Virtual Camera","frequency":2409250048,"gain":-9,"thread_queue":10,"rt_buffer":400,"fifo_size":50,"input_choice":"dshow","audio_codec":"libfdk_aac","audio_sample_rate":"48000","network":"44.0.0.0/24","pc1":"192.168.1.220","pc2":"192.168.1.90","portstart_udp":"4567","portend_udp":"4567","tunip":"44.0.0.3","portstart_tcp":"1880","portend_tcp":"2223","udp_ip_port":"230.0.0.33:9696","rtmp_ip_port":"0.0.0.0:9697","ffplay_console":false,"spectrum":{"gain":27,"max_db":550,"min_db":460,"signal_threshold":41,"averaging":15,"spectrum_percent":60,"color":5,"percent":66,"freq":749.231562,"35ks":560000,"66ks":1056000,"125ks":2000000,"250ks":8000000,"333ks":10656000,"500ks":16000000,"1000ks":16000000,"1500ks":24000000,"2000ks":8000000,"3000ks":12000000,"4000ks":16000000},"audio_device_linux":"plughw:Loopback,1","video_device_linux":"/dev/video0","null_packets":true,"audio_delay":-0.65,"firewall":false,"ffplay_top":892,"audio_delay_vvc":-0.45,"ffplay_left":2972,"ui":{"longmynd":true,"modulator_extra":false,"encoder_extra":false,"info":true,"misc":true,"encoder":true,"ffmpeg":true,"ffplay":true,"longmynd_extra":false,"batc":true,"pluto_spectrum":true,"modulator":true,"presets":true},"remtunnel":"44.0.0.3","remtunport":"1234","nvidia_preset":"18","nvidia_tune":"1","nvidia_profile":"high","libx26x_preset":"6","libx26x_crf":20,"bitrate_multiplier":1,"use_crf":false,"key_frame_multi":5}

73,s de Jabi, ea2aru.

**Comment by Psynosaur** [comment]
Hallo

Redownload the release zip and start over.

Your settings is missing a lot of parameters.

Regards
