### ISSUE TITLE
help again:

### ISSUE THREAD

**Issue by Jabieraru142** [Psynosaur/DATV-Red#31]

**Comment by Jabieraru142** [comment]
Good after again: 
I am toubles un RX with DATV-Red4-9
What are the correct addresses in the settings.json for network, tunin ip, udp_ip_port?. Obvially pc1 and pc2 are the address of my computer.
In the device.json: tsip, configIP, tsip_host?
If I run the DATV-Red and Minitoune, I receive with MPV, Fplay and VLC. Is clear that Minitoune send signal for the UDP 230.0.0.10:11000 in my case. Whay is the correct configuration for receive only with DATV-Red ?
Regards de Jabi, ea2aru.

**Comment by Psynosaur** [comment]
Hi

![image](https://github.com/user-attachments/assets/ccebb717-11bc-41e6-85b7-0ac3fdcfd2e0)

You place your  `230.0.0.10:11000` there.
