### ISSUE TITLE
Command line window stops with error message

### ISSUE THREAD

**Issue by DL3RY** [Psynosaur/DATV-Red#33]
Hello Ohan,
after days and weeks of fine working suddenly V4.93 during startup the command line window stops with following error message:
[error] - [Funktion: Gain :] TypeError: Cannot read properties of undefined (reading 'gain')
After new installation everything is working again but after 3 times of installing new I'm asking for a solution.
Thanks
73's de Achim, DL3RY

**Comment by Psynosaur** [comment]
Hi

Please try latest release, there was small bug regarding settings.

Test and let me know?

**Comment by DL3RY** [comment]
Hi,
new release have been working since yesterday without any issues. If somthing will occur I'll contact you immediately.
Thanks and 73's
Achim, DL3RY
